version: '3.8'

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - /home/ubuntu/.composer-docker/cache:/root/.composer/cache:delegated
      - /home/ubuntu/yii2-app:/app:delegated
    ports:
      - "8080:80"

